import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const scenicSpots = [
  {
    name: '西湖',
    city: '杭州',
    address: '浙江省杭州市西湖区龙井路1号',
    tags: ['免费', '自然', '文化', '情侣'],
    score: 4.8,
    openTime: '全天开放',
    images: ['https://images.unsplash.com/photo-westlake-1.jpg', 'https://images.unsplash.com/photo-westlake-2.jpg'],
    introduction: '西湖位于杭州市西部，是中国十大风景名胜之一，也是世界文化遗产。湖面面积约6.38平方公里，以秀丽的湖光山色和众多的名胜古迹闻名中外。"欲把西湖比西子，淡妆浓抹总相宜"是苏轼对西湖的经典赞美。',
    transport: '公共交通：乘坐地铁1号线到龙翔桥站，步行约10分钟到达湖滨。公交7路、K7路到断桥站下车。\n自驾：导航至西湖景区停车场，建议选择黄龙体育中心停车场。\n步行/骑行：景区内适合步行和骑行游览，可租借公共自行车。',
    ticketInfo: '免费（部分景点收费：灵隐寺30元，雷峰塔40元）',
    phone: '0571-87977767',
    suggestedDuration: '半天至一天',
    source: 'seed',
  },
  {
    name: '故宫博物院',
    city: '北京',
    address: '北京市东城区景山前街4号',
    tags: ['文化', '亲子'],
    score: 4.9,
    openTime: '8:30-17:00（16:00停止入馆，周一闭馆）',
    images: ['https://images.unsplash.com/photo-forbidden-city-1.jpg'],
    introduction: '故宫又称紫禁城，是明清两代的皇宫，也是世界上现存规模最大、保存最为完整的木质结构古建筑群。故宫占地面积72万平方米，建筑面积约15万平方米，有大小宫殿七十多座，房屋九千余间。',
    transport: '公共交通：地铁1号线天安门东站或天安门西站下车，步行即到。\n自驾：故宫周边不建议自驾，停车位极少。建议乘坐公共交通。',
    ticketInfo: '旺季60元，淡季40元（需提前网上预约）',
    phone: '010-85007421',
    suggestedDuration: '半天至一天',
    source: 'seed',
  },
  {
    name: '外滩',
    city: '上海',
    address: '上海市黄浦区中山东一路',
    tags: ['免费', '夜景', '情侣', '文化'],
    score: 4.6,
    openTime: '全天开放',
    images: ['https://images.unsplash.com/photo-bund-1.jpg', 'https://images.unsplash.com/photo-bund-2.jpg'],
    introduction: '外滩是上海的标志性景观，全长约1.5公里，沿黄浦江西岸排列着52幢风格各异的古典复兴大楼，被誉为"万国建筑博览群"。夜晚灯光璀璨，对岸陆家嘴的现代建筑群与外滩古建筑交相辉映。',
    transport: '公共交通：地铁2号线南京东路站，步行约5分钟。地铁10号线豫园站。\n自驾：外滩地下停车场，收费较高。\n步行：南京路步行街尽头即到。',
    ticketInfo: '免费',
    phone: null,
    suggestedDuration: '2-3小时',
    source: 'seed',
  },
  {
    name: '兵马俑',
    city: '西安',
    address: '陕西省西安市临潼区秦陵北路',
    tags: ['文化', '亲子'],
    score: 4.7,
    openTime: '8:30-18:00（3月-11月）；8:30-17:00（12月-次年2月）',
    images: ['https://images.unsplash.com/photo-terracotta-1.jpg'],
    introduction: '秦始皇兵马俑博物馆是中国最大的古代军事博物馆，被誉为"世界第八大奇迹"。共有三个兵马俑坑，出土陶俑8000余件，是研究秦朝军事、政治、经济的珍贵资料。',
    transport: '公共交通：从西安火车站乘坐游5路（306路）直达，约1小时。\n自驾：走连霍高速临潼出口，约40分钟车程。',
    ticketInfo: '120元（含秦始皇帝陵博物院）',
    phone: '029-81399127',
    suggestedDuration: '3-4小时',
    source: 'seed',
  },
  {
    name: '张家界国家森林公园',
    city: '张家界',
    address: '湖南省张家界市武陵源区',
    tags: ['自然', '小众'],
    score: 4.8,
    openTime: '7:00-18:00',
    images: ['https://images.unsplash.com/photo-zhangjiajie-1.jpg', 'https://images.unsplash.com/photo-zhangjiajie-2.jpg'],
    introduction: '张家界国家森林公园是中国第一个国家森林公园，以独特的石英砂岩峰林地貌闻名世界。电影《阿凡达》中悬浮山的原型"乾坤柱"就在此处。园内有金鞭溪、袁家界、天子山等核心景区。',
    transport: '公共交通：张家界荷花机场有大巴到森林公园门票站，约40分钟。火车站有直达巴士。\n自驾：长张高速张家界出口，导航至森林公园门票站。',
    ticketInfo: '225元（四日有效，含景区环保车）',
    phone: '0744-5712189',
    suggestedDuration: '2-3天',
    source: 'seed',
  },
  {
    name: '鼓浪屿',
    city: '厦门',
    address: '福建省厦门市思明区鼓浪屿',
    tags: ['文化', '情侣', '小众'],
    score: 4.5,
    openTime: '全天开放（轮渡有班次时间）',
    images: ['https://images.unsplash.com/photo-gulangyu-1.jpg'],
    introduction: '鼓浪屿是厦门的一座小岛，面积约1.87平方公里，岛上汇集了各种风格的建筑，有"万国建筑博览"之称。2017年被列入世界文化遗产名录。岛上禁止机动车辆，步行探索是最佳方式。',
    transport: '公共交通：从厦门东渡码头（市民航线）或嵩屿码头乘坐轮渡前往，船程约20分钟。\n注意：游客需从东渡国际邮轮中心码头购票乘船，建议网上提前购票。',
    ticketInfo: '上岛船票35元（往返），岛上景点联票100元',
    phone: '0592-2060777',
    suggestedDuration: '半天至一天',
    source: 'seed',
  },
  {
    name: '九寨沟',
    city: '阿坝',
    address: '四川省阿坝藏族羌族自治州九寨沟县漳扎镇',
    tags: ['自然', '小众'],
    score: 4.9,
    openTime: '8:30-17:00（旺季），9:00-16:00（淡季）',
    images: ['https://images.unsplash.com/photo-jiuzhaigou-1.jpg', 'https://images.unsplash.com/photo-jiuzhaigou-2.jpg'],
    introduction: '九寨沟以翠海、叠瀑、彩林、雪峰、藏情"五绝"驰名中外，被誉为"人间仙境"、"童话世界"。沟内遍布原始森林，分布着108个湖泊和众多瀑布。1992年被列入世界自然遗产。',
    transport: '公共交通：九寨黄龙机场有班车到景区，约1.5小时。成都新南门汽车站有直达大巴。\n自驾：成都出发走都汶高速+G213国道，约8小时车程。',
    ticketInfo: '旺季169元+观光车90元，淡季80元+观光车80元',
    phone: '0837-7739753',
    suggestedDuration: '1-2天',
    source: 'seed',
  },
  {
    name: '长城（八达岭）',
    city: '北京',
    address: '北京市延庆区G6京藏高速58号出口',
    tags: ['文化', '亲子'],
    score: 4.7,
    openTime: '6:30-19:00（4月-10月），7:00-18:00（11月-3月）',
    images: ['https://images.unsplash.com/photo-greatwall-1.jpg'],
    introduction: '八达岭长城是明长城中保存最好的一段，也是最具代表性的一段。这里地势险要，城关坚固，是万里长城的精华所在。"不到长城非好汉"已成为中外游客的必到之处。',
    transport: '公共交通：德胜门乘坐877路快车直达，约1小时。S2线列车从北京北站出发。\n自驾：京藏高速（G6）58号出口，约1.5小时车程。',
    ticketInfo: '旺季40元，淡季35元',
    phone: '010-69121226',
    suggestedDuration: '3-5小时',
    source: 'seed',
  },
  {
    name: '丽江古城',
    city: '丽江',
    address: '云南省丽江市古城区',
    tags: ['文化', '情侣', '夜景'],
    score: 4.4,
    openTime: '全天开放',
    images: ['https://images.unsplash.com/photo-lijiang-1.jpg', 'https://images.unsplash.com/photo-lijiang-2.jpg'],
    introduction: '丽江古城始建于宋末元初，是中国保存最为完整的纳西族古城。古城以"家家流水、户户垂柳"的高原水乡风貌著称，1997年被列入世界文化遗产名录。夜晚的酒吧街和四方街热闹非凡。',
    transport: '公共交通：丽江三义机场有大巴到古城，约40分钟。火车站有公交到古城口。\n自驾：古城内禁止车辆通行，需停在古城外停车场。',
    ticketInfo: '免费（古城维护费已取消）',
    phone: '0888-5111118',
    suggestedDuration: '1-2天',
    source: 'seed',
  },
  {
    name: '西安城墙',
    city: '西安',
    address: '陕西省西安市碑林区南大街',
    tags: ['文化', '免费', '亲子'],
    score: 4.5,
    openTime: '8:00-22:00（南门），8:00-19:00（其他门）',
    images: ['https://images.unsplash.com/photo-xian-wall-1.jpg'],
    introduction: '西安城墙是中国现存最完整的古代城垣，始建于明洪武年间，全长约13.74公里。登上城墙可以骑自行车环绕一周，俯瞰古城全貌。南门（永宁门）是最壮观的城门。',
    transport: '公共交通：地铁2号线永宁门站即到南门。多条公交到达各个城门。\n自驾：城墙周边有停车场，建议从南门或北门进入。',
    ticketInfo: '54元（含城墙门票），自行车租赁另计45元/100分钟',
    phone: '029-87272792',
    suggestedDuration: '2-3小时',
    source: 'seed',
  },
  {
    name: '洱海',
    city: '大理',
    address: '云南省大理白族自治州大理市',
    tags: ['自然', '情侣', '免费'],
    score: 4.6,
    openTime: '全天开放',
    images: ['https://images.unsplash.com/photo-erhai-1.jpg', 'https://images.unsplash.com/photo-erhai-2.jpg'],
    introduction: '洱海是云南第二大淡水湖，湖面面积约256平方公里。环洱海骑行是大理最受欢迎的体验之一，沿途可欣赏苍山洱海的绝美风光。双廊、喜洲、海舌公园等环湖景点各具特色。',
    transport: '公共交通：大理古城有公交到才村码头。环海可租电动车或包车。\n自驾：环海公路全程约130公里，风景优美适合自驾。\n骑行：古城多处可租赁电动车/自行车，环湖约需6-8小时。',
    ticketInfo: '免费（游船另计）',
    phone: null,
    suggestedDuration: '1天',
    source: 'seed',
  },
  {
    name: '黄山',
    city: '黄山',
    address: '安徽省黄山市黄山区汤口镇',
    tags: ['自然'],
    score: 4.8,
    openTime: '6:00-17:30（周一至周五），6:00-17:30（周末）',
    images: ['https://images.unsplash.com/photo-huangshan-1.jpg'],
    introduction: '黄山以奇松、怪石、云海、温泉"四绝"闻名天下，被联合国教科文组织列入世界自然与文化双遗产。主要景区包括玉屏楼、光明顶、飞来石、西海大峡谷等。徐霞客曾赞叹"登黄山，天下无山"。',
    transport: '公共交通：黄山北站有旅游专线到汤口换乘中心，约50分钟。\n自驾：京台高速汤口出口，导航至黄山风景区南大门。\n索道：前山玉屏索道，后山云谷索道，西海大峡谷地轨。',
    ticketInfo: '旺季190元，淡季150元（索道单程另计80-100元）',
    phone: '0559-5580327',
    suggestedDuration: '2天（建议山上住一晚看日出）',
    source: 'seed',
  },
  {
    name: '成都大熊猫繁育研究基地',
    city: '成都',
    address: '四川省成都市成华区熊猫大道1375号',
    tags: ['亲子', '自然'],
    score: 4.6,
    openTime: '7:30-18:00（16:00停止入园）',
    images: ['https://images.unsplash.com/photo-panda-1.jpg', 'https://images.unsplash.com/photo-panda-2.jpg'],
    introduction: '成都大熊猫繁育研究基地是全球最大的大熊猫人工繁育机构，园内饲养了100多只大熊猫及小熊猫。建议早上8-10点前往，此时大熊猫最活跃。月亮产房可看到熊猫幼仔。',
    transport: '公共交通：地铁3号线熊猫大道站，步行约15分钟或乘摆渡车。\n自驾：导航至熊猫基地停车场，旺季停车位紧张建议早到。',
    ticketInfo: '55元（网上预约）',
    phone: '028-83510033',
    suggestedDuration: '3-4小时',
    source: 'seed',
  },
  {
    name: '西塘古镇',
    city: '嘉兴',
    address: '浙江省嘉兴市嘉善县西塘镇',
    tags: ['文化', '小众', '夜景', '情侣'],
    score: 4.3,
    openTime: '全天开放（收费景点8:00-17:00）',
    images: ['https://images.unsplash.com/photo-xitang-1.jpg'],
    introduction: '西塘古镇是江南六大古镇之一，以"桥多、弄多、廊棚多"闻名。1000多米的烟雨长廊是古镇最大的特色。夜晚的酒吧街和灯光映射的水面构成迷人夜景。',
    transport: '公共交通：嘉善站/嘉善南站有公交K215到西塘，约20分钟。上海南站有直达班车。\n自驾：沪昆高速嘉善大云出口，约15分钟到景区。',
    ticketInfo: '50元（含11个小景点，夜间17:00后免费入镇）',
    phone: '0573-84567890',
    suggestedDuration: '半天至一天',
    source: 'seed',
  },
  {
    name: '鸟巢（国家体育场）',
    city: '北京',
    address: '北京市朝阳区国家体育场南路1号',
    tags: ['文化', '亲子'],
    score: 4.2,
    openTime: '9:00-21:00',
    images: ['https://images.unsplash.com/photo-birdsnest-1.jpg'],
    introduction: '国家体育场（鸟巢）是2008年北京奥运会的主体育场，由赫尔佐格和德梅隆设计。钢结构外观形似鸟巢，是北京的标志性建筑之一。内部可参观比赛场地和奥运展览。',
    transport: '公共交通：地铁8号线奥体中心站或奥林匹克公园站，步行约10分钟。\n自驾：奥林匹克公园地下停车场。',
    ticketInfo: '50元（外观免费参观）',
    phone: '010-84373008',
    suggestedDuration: '1-2小时',
    source: 'seed',
  },
  {
    name: '武夷山',
    city: '南平',
    address: '福建省南平市武夷山市武夷山国家公园',
    tags: ['自然', '文化', '小众'],
    score: 4.7,
    openTime: '6:30-18:00',
    images: ['https://images.unsplash.com/photo-wuyishan-1.jpg'],
    introduction: '武夷山是世界自然与文化双遗产，以丹霞地貌和茶文化闻名。九曲溪竹筏漂流是最具特色的体验项目，全程约9.5公里，可沿途欣赏36峰99岩的壮丽景观。天游峰被称为"武夷第一险峰"。',
    transport: '公共交通：武夷山北站（高铁）有旅游专线到景区南入口，约15分钟。\n自驾：京台高速武夷山出口。',
    ticketInfo: '一日票140元，二日票150元（竹筏漂流另计100元）',
    phone: '0599-5131890',
    suggestedDuration: '2天',
    source: 'seed',
  },
  {
    name: '青海湖',
    city: '海南州',
    address: '青海省海南藏族自治州共和县',
    tags: ['自然', '小众', '免费'],
    score: 4.7,
    openTime: '全天开放',
    images: ['https://images.unsplash.com/photo-qinghai-lake-1.jpg'],
    introduction: '青海湖是中国最大的内陆湖和咸水湖，湖面面积约4500平方公里。每年7-8月是最佳观赏季节，油菜花盛开，湖水湛蓝。环湖骑行全程约360公里，是骑行爱好者的天堂。',
    transport: '公共交通：西宁有旅游大巴到二郎剑景区，约2.5小时。\n自驾：从西宁走京藏高速转G109国道，约150公里。环湖公路路况良好。\n包车：西宁出发环湖一日游包车约400-600元。',
    ticketInfo: '二郎剑景区90元（湖边其他区域免费）',
    phone: null,
    suggestedDuration: '1-2天',
    source: 'seed',
  },
  {
    name: '千岛湖',
    city: '杭州',
    address: '浙江省杭州市淳安县',
    tags: ['自然', '亲子'],
    score: 4.5,
    openTime: '8:00-17:00',
    images: ['https://images.unsplash.com/photo-qiandaohu-1.jpg'],
    introduction: '千岛湖因有1078个岛屿而得名，水质优良达到可直接饮用标准。湖区面积573平方公里，是长三角地区最大的人工湖。主要游玩方式为乘坐游船登岛游览，梅峰岛可俯瞰千岛全景。',
    transport: '公共交通：杭州汽车西站有班车到淳安，约2小时。千岛湖站（高铁）有接驳巴士。\n自驾：杭新景高速千岛湖出口，约2.5小时。',
    ticketInfo: '中心湖区游船票150元（含3个岛屿）',
    phone: '0571-64811218',
    suggestedDuration: '1天',
    source: 'seed',
  },
  {
    name: '颐和园',
    city: '北京',
    address: '北京市海淀区新建宫门路19号',
    tags: ['文化', '亲子', '自然'],
    score: 4.6,
    openTime: '6:30-18:00（4月-10月），7:00-17:00（11月-3月）',
    images: ['https://images.unsplash.com/photo-summer-palace-1.jpg'],
    introduction: '颐和园是中国现存最大的皇家园林，前身为清漪园，以昆明湖和万寿山为基础构建。长廊全长728米，是世界上最长的画廊，绘有14000余幅彩画。园内还有佛香阁、十七孔桥等经典建筑。',
    transport: '公共交通：地铁4号线北宫门站，步行5分钟到北宫门入口。或西苑站到东宫门。\n自驾：颐和园停车场位于新建宫门附近。',
    ticketInfo: '旺季30元，淡季20元（联票60元含园中园）',
    phone: '010-62881144',
    suggestedDuration: '3-5小时',
    source: 'seed',
  },
  {
    name: '橘子洲',
    city: '长沙',
    address: '湖南省长沙市岳麓区橘子洲头',
    tags: ['免费', '文化', '自然'],
    score: 4.4,
    openTime: '全天开放',
    images: ['https://images.unsplash.com/photo-orange-island-1.jpg'],
    introduction: '橘子洲位于湘江中央，是世界上最大的内陆洲。洲头矗立着32米高的毛泽东青年艺术雕塑，是长沙的标志性景点。毛泽东曾在此写下"独立寒秋，湘江北去，橘子洲头"的豪迈词句。',
    transport: '公共交通：地铁2号线橘子洲站，出站即到景区入口。\n自驾：橘子洲大桥旁有停车场，但节假日限流建议地铁。\n景区内：免费观光小火车往返。',
    ticketInfo: '免费',
    phone: '0731-88882152',
    suggestedDuration: '2-3小时',
    source: 'seed',
  },
  {
    name: '三亚亚龙湾',
    city: '三亚',
    address: '海南省三亚市吉阳区亚龙湾国家旅游度假区',
    tags: ['自然', '情侣', '亲子'],
    score: 4.5,
    openTime: '全天开放（海滩）',
    images: ['https://images.unsplash.com/photo-yalong-bay-1.jpg', 'https://images.unsplash.com/photo-yalong-bay-2.jpg'],
    introduction: '亚龙湾被称为"天下第一湾"，是三亚最优质的海滩之一。这里沙质细腻洁白，海水清澈湛蓝，能见度7-9米。海湾呈月牙形，全长约7.5公里。适合游泳、潜水、沙滩运动等多种水上活动。',
    transport: '公共交通：三亚凤凰机场乘27路公交到亚龙湾，约1小时。市区25/15路公交直达。\n自驾：海南环岛高速亚龙湾出口。\n打车：从三亚市区打车约30分钟，费用约50-80元。',
    ticketInfo: '海滩免费（部分酒店私属沙滩需通过酒店进入）',
    phone: null,
    suggestedDuration: '半天至一天',
    source: 'seed',
  },
  {
    name: '拙政园',
    city: '苏州',
    address: '江苏省苏州市姑苏区东北街178号',
    tags: ['文化', '小众'],
    score: 4.5,
    openTime: '7:30-17:30（3月-11月），7:30-17:00（12月-2月）',
    images: ['https://images.unsplash.com/photo-humble-admin-1.jpg'],
    introduction: '拙政园是苏州四大名园之首，也是中国四大名园之一，始建于明正德年间。园以水为中心，山水萦绕、厅榭精美，被誉为"中国园林之母"。1997年被列入世界文化遗产。',
    transport: '公共交通：地铁4号线北寺塔站，步行约10分钟。公交游1、游2路到拙政园站。\n自驾：姑苏区停车位紧张，建议公共交通。',
    ticketInfo: '旺季70元，淡季50元',
    phone: '0512-67510286',
    suggestedDuration: '2-3小时',
    source: 'seed',
  },
  {
    name: '稻城亚丁',
    city: '甘孜',
    address: '四川省甘孜藏族自治州稻城县香格里拉镇',
    tags: ['自然', '小众'],
    score: 4.8,
    openTime: '7:00-18:30（旺季），8:00-17:30（淡季）',
    images: ['https://images.unsplash.com/photo-daocheng-1.jpg', 'https://images.unsplash.com/photo-daocheng-2.jpg'],
    introduction: '稻城亚丁被誉为"蓝色星球上的最后一片净土"，以三座神山（仙乃日、央迈勇、夏诺多吉）和高山湖泊（牛奶海、五色海）闻名。这里的秋天色彩斑斓，是摄影爱好者的天堂。海拔较高，注意高反。',
    transport: '公共交通：稻城亚丁机场（海拔4411米）有班车到景区。成都有直飞航班约1小时。\n自驾：成都出发走G318川藏线或G227，约2天车程（需适应海拔）。\n建议：从成都飞稻城，再包车到景区。',
    ticketInfo: '旺季146元+观光车120元，淡季120元+观光车120元',
    phone: '0836-6966022',
    suggestedDuration: '2-3天',
    source: 'seed',
  },
  {
    name: '南京夫子庙',
    city: '南京',
    address: '江苏省南京市秦淮区秦淮河畔',
    tags: ['文化', '美食', '夜景', '免费'],
    score: 4.3,
    openTime: '全天开放（部分场馆有时间限制）',
    images: ['https://images.unsplash.com/photo-confucius-temple-1.jpg'],
    introduction: '夫子庙是供奉祭祀孔子的庙宇，始建于1034年。秦淮河畔的夫子庙-秦淮风光带是南京最热闹的商业街区，汇集了众多金陵小吃和民间工艺品店。夜晚的秦淮河画舫别有风情。',
    transport: '公共交通：地铁3号线夫子庙站，出站即到。多条公交到达。\n自驾：附近停车场较多但节假日拥挤。',
    ticketInfo: '景区免费（秦淮河画舫80元，江南贡院30元）',
    phone: '025-52209788',
    suggestedDuration: '3-4小时',
    source: 'seed',
  },
  {
    name: '布达拉宫',
    city: '拉萨',
    address: '西藏自治区拉萨市城关区北京中路35号',
    tags: ['文化', '小众'],
    score: 4.9,
    openTime: '9:00-16:00（15:00停止入宫）',
    images: ['https://images.unsplash.com/photo-potala-1.jpg'],
    introduction: '布达拉宫是世界上海拔最高的宫殿，也是西藏最庞大、最完整的古代宫堡建筑群。始建于公元7世纪，是藏传佛教的圣地。宫殿依山而建，气势恢宏，内部珍藏大量文物和壁画。注意高海拔（3700米）。',
    transport: '公共交通：拉萨贡嘎机场有大巴到市区，约1小时。市内公交8路到布达拉宫站。\n步行：从大昭寺步行约20分钟。\n注意：参观需提前1天预约（旺季），按预约时间入宫。',
    ticketInfo: '旺季200元（5-10月，需预约），淡季100元',
    phone: '0891-6822896',
    suggestedDuration: '2-3小时',
    source: 'seed',
  },
  {
    name: '重庆洪崖洞',
    city: '重庆',
    address: '重庆市渝中区嘉陵江滨江路88号',
    tags: ['免费', '夜景', '美食', '文化'],
    score: 4.4,
    openTime: '全天开放（商铺10:00-22:00）',
    images: ['https://images.unsplash.com/photo-hongyadong-1.jpg', 'https://images.unsplash.com/photo-hongyadong-2.jpg'],
    introduction: '洪崖洞是重庆最具特色的吊脚楼建筑群，依山就势层叠而建，共11层。夜晚灯光亮起时犹如《千与千寻》中的场景。内部集合了重庆特色美食、酒吧和民俗文化体验。',
    transport: '公共交通：地铁1号线小什字站或6号线大剧院站，步行约5-10分钟。\n自驾：洪崖洞无停车场，建议停在附近商圈。\n步行：解放碑步行约10分钟到达。',
    ticketInfo: '免费',
    phone: '023-63039999',
    suggestedDuration: '2-3小时',
    source: 'seed',
  },
  {
    name: '西双版纳热带植物园',
    city: '西双版纳',
    address: '云南省西双版纳傣族自治州勐腊县勐仑镇',
    tags: ['自然', '亲子', '小众'],
    score: 4.6,
    openTime: '8:00-18:00',
    images: ['https://images.unsplash.com/photo-xishuangbanna-1.jpg'],
    introduction: '中国科学院西双版纳热带植物园是中国最大的植物园，占地约1125公顷。园内收集了13000多种热带植物，包括见血封喉、跳舞草、望天树等珍稀植物。是了解热带雨林生态的绝佳去处。',
    transport: '公共交通：景洪客运站有班车到勐仑镇，约1.5小时。植物园东门有接驳车。\n自驾：从景洪走昆磨高速勐仑出口，约50分钟。',
    ticketInfo: '80元（电瓶车50元）',
    phone: '0691-8715914',
    suggestedDuration: '半天至一天',
    source: 'seed',
  },
  {
    name: '平遥古城',
    city: '晋中',
    address: '山西省晋中市平遥县',
    tags: ['文化', '小众'],
    score: 4.5,
    openTime: '8:00-18:00（古城全天可进入，景点有时间限制）',
    images: ['https://images.unsplash.com/photo-pingyao-1.jpg'],
    introduction: '平遥古城是中国保存最为完好的古代县城之一，始建于西周。1997年被列入世界文化遗产。古城内有完整的城墙、县衙、票号、镖局等明清建筑群。日升昌票号是中国第一家票号（银行前身）。',
    transport: '公共交通：平遥古城站（高铁）距古城约8公里，出站有公交和出租车。太原有动车约40分钟到达。\n自驾：京昆高速平遥出口，古城内禁止机动车。',
    ticketInfo: '125元（含22个景点通票，3日有效）',
    phone: '0354-5690000',
    suggestedDuration: '1-2天',
    source: 'seed',
  },
  {
    name: '东方明珠',
    city: '上海',
    address: '上海市浦东新区世纪大道1号',
    tags: ['夜景', '亲子'],
    score: 4.3,
    openTime: '9:00-21:00',
    images: ['https://images.unsplash.com/photo-oriental-pearl-1.jpg'],
    introduction: '东方明珠广播电视塔高468米，是上海的标志性建筑。塔内设有多层观光层，263米处的全透明悬空观光廊可俯瞰浦江两岸全景。259米处的旋转餐厅可边用餐边360度观赏上海风光。',
    transport: '公共交通：地铁2号线陆家嘴站，步行约5分钟。\n自驾：正大广场地下停车场或周边商场停车。\n轮渡：从外滩乘坐过江轮渡到达陆家嘴码头。',
    ticketInfo: '199元（含三球观光），259元（含旋转餐厅）',
    phone: '021-58791888',
    suggestedDuration: '2-3小时',
    source: 'seed',
  },
  {
    name: '桂林漓江',
    city: '桂林',
    address: '广西壮族自治区桂林市',
    tags: ['自然', '情侣'],
    score: 4.7,
    openTime: '8:30-16:30（竹筏/游船）',
    images: ['https://images.unsplash.com/photo-lijiang-river-1.jpg', 'https://images.unsplash.com/photo-lijiang-river-2.jpg'],
    introduction: '桂林山水甲天下，漓江是桂林风光的精华所在。从桂林到阳朔全程83公里，沿途可欣赏九马画山、黄布倒影、二十元人民币背景图等经典景观。竹筏漂流是最惬意的游览方式。',
    transport: '公共交通：桂林磨盘山码头有游船到阳朔，约4小时。杨堤码头有竹筏到兴坪，约1.5小时。\n自驾：不适合自驾游览，建议游船或竹筏。\n推荐：杨堤-兴坪段竹筏漂流最精华。',
    ticketInfo: '竹筏漂流216元/人（杨堤-兴坪段），游船210-350元',
    phone: '0773-2825502',
    suggestedDuration: '半天至一天',
    source: 'seed',
  },
  {
    name: '长隆野生动物世界',
    city: '广州',
    address: '广东省广州市番禺区大石镇',
    tags: ['亲子', '自然'],
    score: 4.6,
    openTime: '9:30-18:00（周一至周五），9:30-18:30（周末）',
    images: ['https://images.unsplash.com/photo-chimelong-1.jpg'],
    introduction: '长隆野生动物世界是中国最大的野生动物主题公园，拥有500多种2万余只珍稀动物。园区分为步行区和自驾车游览区。最受欢迎的动物明星包括大熊猫三胞胎、白虎和考拉等。',
    transport: '公共交通：地铁3号线/7号线汉溪长隆站，免费穿梭巴士到各园区。\n自驾：南沙港快速路长隆出口。园区有大型停车场。',
    ticketInfo: '全票350元（网上预订有优惠），儿童/老人245元',
    phone: '020-84783333',
    suggestedDuration: '一天',
    source: 'seed',
  },
];

const spotReviews = [
  // 西湖评价
  { spotIndex: 0, score: 5, content: '西湖真的太美了！断桥残雪虽然没看到雪，但湖边的柳树和远处的山景让人心旷神怡。建议租一辆自行车环湖骑行。', images: [] },
  { spotIndex: 0, score: 4, content: '人很多，尤其是周末。但风景确实美，免费这一点很良心。雷峰塔需要另外买票，建议傍晚去看日落。', images: [] },
  { spotIndex: 0, score: 5, content: '带娃来的，西湖边有很多适合孩子的活动。花港观鱼可以喂鱼，小朋友很开心。', images: [] },
  // 故宫评价
  { spotIndex: 1, score: 5, content: '太震撼了！一定要提前网上买票，旺季经常一票难求。建议跟着讲解器走，不然很多历史细节会错过。', images: [] },
  { spotIndex: 1, score: 5, content: '第二次来故宫了，这次走了珍宝馆和钟表馆，非常值得。建议至少留半天时间慢慢逛。', images: [] },
  { spotIndex: 1, score: 4, content: '建筑很宏伟，但人太多了。建议淡季或工作日来，体验会好很多。午门进，神武门出，不走回头路。', images: [] },
  // 外滩评价
  { spotIndex: 2, score: 5, content: '夜景绝了！对面陆家嘴的灯光秀配合外滩的老建筑，真的是上海最美的地方。晚上8点左右来最好。', images: [] },
  { spotIndex: 2, score: 4, content: '白天和晚上完全是两种风格，都值得来。人多到爆，建议工作日晚上来。', images: [] },
  // 兵马俑评价
  { spotIndex: 3, score: 5, content: '世界第八大奇迹名不虚传！一号坑最壮观，一定要请导游讲解，不然就是看泥人。', images: [] },
  { spotIndex: 3, score: 4, content: '值得来一次，但看完就不会想来第二次了。铜车马展厅新修了很漂亮。', images: [] },
  // 张家界评价
  { spotIndex: 4, score: 5, content: '仙境！袁家界的景色太震撼了，云雾缭绕的时候真的像阿凡达的世界。建议住景区内节省时间。', images: [] },
  { spotIndex: 4, score: 5, content: '西海大峡谷必去！虽然走下去很累但风景绝对值得。建议穿好走的鞋子，带够水。', images: [] },
  // 鼓浪屿评价
  { spotIndex: 5, score: 4, content: '文艺小岛，适合拍照。建议避开节假日来，平时人少很舒服。岛上的小吃很多但价格偏贵。', images: [] },
  { spotIndex: 5, score: 4, content: '日光岩值得爬，可以俯瞰整个岛。风琴博物馆很有特色。记得提前买船票！', images: [] },
  // 九寨沟评价
  { spotIndex: 6, score: 5, content: '人间仙境！五花海的颜色简直不真实，像打翻了调色盘。秋天来最美，各种颜色层次分明。', images: [] },
  { spotIndex: 6, score: 5, content: '去了两次，每个季节都有不同的美。建议先坐车到最远处，然后一路走下来拍照。', images: [] },
  // 长城评价
  { spotIndex: 7, score: 5, content: '不到长城非好汉！八达岭比较好爬，设施完善。北段人少风景好，建议早上早点来避开人流。', images: [] },
  { spotIndex: 7, score: 4, content: '确实壮观，但真的很累。建议坐缆车上去再往两边走。人超级多，工作日好一些。', images: [] },
  // 丽江古城评价
  { spotIndex: 8, score: 4, content: '古城白天逛逛小店很惬意，晚上酒吧街太嗨了。商业化比较严重但还是值得来一次。', images: [] },
  { spotIndex: 8, score: 3, content: '人太多了，而且商业化严重。不过远离酒吧街的小巷子里还是能找到安静的角落。', images: [] },
  // 洱海评价
  { spotIndex: 10, score: 5, content: '环洱海骑行太爽了！蓝天白云配碧蓝的湖水，心情超好。双廊那边的网红S弯很适合拍照。', images: [] },
  { spotIndex: 10, score: 4, content: '建议租电动车环湖，骑自行车太累了（一圈130公里）。才村和喜洲古镇值得停留。', images: [] },
  // 黄山评价
  { spotIndex: 11, score: 5, content: '登黄山天下无山！日出和云海太震撼了，一定要在山上住一晚。西海大峡谷是精华中的精华。', images: [] },
  // 大熊猫基地评价
  { spotIndex: 12, score: 5, content: '大熊猫太可爱了！一定要早上8点到，那时候熊猫在吃早餐最活跃。月亮产房能看到小熊猫宝宝！', images: [] },
  { spotIndex: 12, score: 4, content: '带娃来的，孩子玩了一整天还不想走。建议夏天来的话选凉快的时候，熊猫怕热中午都躲起来了。', images: [] },
];

async function main() {
  console.log('🌱 开始播种景点数据...');

  // 清理旧数据
  await prisma.spotReview.deleteMany();
  await prisma.spotFavorite.deleteMany();
  await prisma.scenicSpot.deleteMany();

  // 创建景点
  const createdSpots = [];
  for (const spot of scenicSpots) {
    const created = await prisma.scenicSpot.create({
      data: {
        name: spot.name,
        city: spot.city,
        address: spot.address,
        tags: spot.tags,
        score: spot.score,
        openTime: spot.openTime,
        images: spot.images,
        introduction: spot.introduction,
        transport: spot.transport,
        ticketInfo: spot.ticketInfo,
        phone: spot.phone,
        suggestedDuration: spot.suggestedDuration,
        source: spot.source,
      },
    });
    createdSpots.push(created);
    console.log(`  ✓ ${created.name} (${created.city})`);
  }

  // 创建一个种子用户用于评价（如果不存在）
  let seedUser = await prisma.user.findFirst({ where: { email: 'seed@tuling.app' } });
  if (!seedUser) {
    seedUser = await prisma.user.create({
      data: {
        email: 'seed@tuling.app',
        passwordHash: '$2b$12$placeholder.hash.for.seed.user.only',
        nickname: '途灵体验官',
        status: 'active',
      },
    });
    console.log(`  ✓ 创建种子用户: ${seedUser.nickname}`);
  }

  // 创建评价
  for (const review of spotReviews) {
    const spot = createdSpots[review.spotIndex];
    await prisma.spotReview.create({
      data: {
        spotId: spot.id,
        userId: seedUser.id,
        score: review.score,
        content: review.content,
        images: review.images,
        status: 'approved',
      },
    });
  }
  console.log(`  ✓ 创建了 ${spotReviews.length} 条评价`);

  console.log(`\n🎉 播种完成！共创建 ${createdSpots.length} 个景点，${spotReviews.length} 条评价`);
}

main()
  .catch((e) => {
    console.error('❌ 播种失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
